-- 1. CLEANUP
DROP TABLE IF EXISTS public.messages CASCADE;
DROP TABLE IF EXISTS public.articles CASCADE;
DROP TABLE IF EXISTS public.competitions CASCADE;
DROP TABLE IF EXISTS public.players CASCADE;
DROP TABLE IF EXISTS public.countries CASCADE;

-- 2. CREATE TABLES
CREATE TABLE public.countries (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug text NOT NULL UNIQUE,
  name text NOT NULL UNIQUE,
  code text NOT NULL UNIQUE,
  flag text NOT NULL,
  image text NOT NULL,
  federation text NOT NULL,
  clubs integer DEFAULT 0,
  players integer DEFAULT 0,
  description text,
  tags text[] DEFAULT '{}',
  created_at timestamptz DEFAULT now()
);

CREATE TABLE public.players (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug text NOT NULL UNIQUE,
  name text NOT NULL,
  country_id bigint REFERENCES public.countries(id) ON DELETE SET NULL,
  image text NOT NULL,
  ranking integer DEFAULT 0,
  rating integer DEFAULT 0,
  titles text[] DEFAULT '{}',
  tags text[] DEFAULT '{}',
  bio text,
  club text,
  featured boolean DEFAULT false,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE public.articles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug text NOT NULL UNIQUE,
  title text NOT NULL,
  excerpt text NOT NULL,
  content text NOT NULL,
  image text NOT NULL,
  category text NOT NULL,
  tags text[] DEFAULT '{}',
  country_id bigint REFERENCES public.countries(id) ON DELETE SET NULL,
  author text NOT NULL,
  author_image text NOT NULL,
  published_at timestamptz NOT NULL DEFAULT now(),
  read_time text NOT NULL,
  featured boolean DEFAULT false,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE public.competitions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug text NOT NULL UNIQUE,
  name text NOT NULL,
  location text NOT NULL,
  country_id bigint REFERENCES public.countries(id) ON DELETE SET NULL,
  start_date timestamptz NOT NULL,
  end_date timestamptz NOT NULL,
  status text NOT NULL CHECK (status IN ('upcoming', 'ongoing', 'completed')),
  image text NOT NULL,
  description text NOT NULL,
  participants integer DEFAULT 0,
  type text NOT NULL,
  tags text[] DEFAULT '{}',
  results jsonb DEFAULT '[]',
  created_at timestamptz DEFAULT now()
);

CREATE TABLE public.messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  email text NOT NULL,
  subject text NOT NULL,
  content text NOT NULL,
  read boolean DEFAULT false,
  tag text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE public.submission_rate_limits (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ip_hash text NOT NULL,
  route text NOT NULL,
  window_start timestamptz NOT NULL DEFAULT date_trunc('hour', now()),
  attempts integer NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT submission_rate_limits_unique_window UNIQUE (ip_hash, route, window_start)
);

-- 3. INSERT COUNTRIES (10)
INSERT INTO public.countries (slug, name, code, flag, image, federation, clubs, players, description, tags) VALUES 
('senegal', 'Sénégal', 'SN', '🇸🇳', '/images/country-senegal.jpg', 'Fédération Sénégalaise de Scrabble', 45, 1200, 'Leader incontesté du Scrabble en Afrique de l''Ouest.', ARRAY['Leader', 'Palmarès', 'Elite']),
('cote-ivoire', 'Côte d''Ivoire', 'CI', '🇨🇮', '/images/country-cotedivoire.jpg', 'Fédération Ivoirienne de Scrabble', 38, 950, 'Une terre de champions avec une infrastructure solide.', ARRAY['Tradition', 'Formateurs']),
('cameroun', 'Cameroun', 'CM', '🇨🇲', '/images/country-cameroun.jpg', 'Fédération Camerounaise de Scrabble', 32, 820, 'Une force montante avec une jeunesse très active.', ARRAY['Dynamisme', 'Afrique Centrale']),
('gabon', 'Gabon', 'GA', '🇬🇦', '/images/hero-scrabble.jpg', 'Fédération Gabonaise de Scrabble', 12, 340, 'Le Gabon se distingue par ses talents techniques.', ARRAY['Technique', 'Emergeant']),
('congo', 'Congo-Brazzaville', 'CG', '🇨🇬', '/images/community.jpg', 'Fédération Congolaise de Scrabble', 15, 410, 'Une communauté passionnée et en pleine croissance.', ARRAY['Passion', 'Communauté']),
('benin', 'Bénin', 'BJ', '🇧🇯', '/images/scrabble-tiles.jpg', 'Fédération Béninoise de Scrabble', 22, 580, 'Le Bénin possède l''un des meilleurs programmes scolaires.', ARRAY['Formation', 'Jeunesse']),
('togo', 'Togo', 'TG', '🇹🇬', '/images/tournament.jpg', 'Fédération Togolaise de Scrabble', 18, 450, 'Le Togo mise sur l''innovation et les tournois numériques.', ARRAY['Innovation', 'Digital']),
('mali', 'Mali', 'ML', '🇲🇱', '/images/player2.jpg', 'Fédération Malienne de Scrabble', 14, 390, 'Une résilience exemplaire et un niveau de jeu relevé.', ARRAY['Résilience', 'Compétition']),
('burkina-faso', 'Burkina Faso', 'BF', '🇧🇫', '/images/player3.jpg', 'Fédération Burkinabé de Scrabble', 20, 520, 'Le Burkina est un acteur majeur des compétitions régionales.', ARRAY['Régional', 'Engagement']),
('niger', 'Niger', 'NE', '🇳🇪', '/images/player4.jpg', 'Fédération Nigérienne de Scrabble', 10, 280, 'Un développement constant et une fédération très structurée.', ARRAY['Structure', 'Avenir']);

-- 4. INSERT PLAYERS (20)
INSERT INTO public.players (slug, name, country_id, image, ranking, rating, titles, tags, bio, club, featured) VALUES 
('ndongo-samba-sylla', 'Ndongo Samba Sylla', (SELECT id FROM public.countries WHERE slug='senegal'), '/images/player1.jpg', 1, 2185, ARRAY['Champion d''Afrique 2024', 'Grand Maître'], ARRAY['Légende', 'Sénégal'], 'L''un des plus grands joueurs de l''histoire.', 'Dakar Scrabble Club', true),
('abibou-fall', 'Abibou Fall', (SELECT id FROM public.countries WHERE slug='senegal'), '/images/player2.jpg', 2, 2140, ARRAY['Vice-champion 2024'], ARRAY['Elite', 'Technicien'], 'Expert en duplicate.', 'Club de Saint-Louis', false),
('mamadou-diop', 'Mamadou Diop', (SELECT id FROM public.countries WHERE slug='cote-ivoire'), '/images/player3.jpg', 3, 2115, ARRAY['Champion de CI 2023'], ARRAY['Ivoirien', 'Top 5'], 'Un joueur agressif et talentueux.', 'Abidjan Elite', true),
('jean-marc-ndouma', 'Jean-Marc Ndouma', (SELECT id FROM public.countries WHERE slug='cameroun'), '/images/player4.jpg', 4, 2090, ARRAY['Champion du Cameroun'], ARRAY['Cameroun', 'Solide'], 'Spécialiste du blitz.', 'Yaoundé Scrabble', false),
('alois-moussavou', 'Aloïs Moussavou', (SELECT id FROM public.countries WHERE slug='gabon'), '/images/player1.jpg', 5, 2075, ARRAY['Champion d''Afrique Centrale'], ARRAY['Gabon', 'Vitesse'], 'Une rapidité de réflexion hors pair.', 'Libreville Club', false),
('samuel-kouame', 'Samuel Kouamé', (SELECT id FROM public.countries WHERE slug='cote-ivoire'), '/images/player2.jpg', 6, 2060, ARRAY['Vainqueur Master Abidjan'], ARRAY['Ivoirien', 'Etoile'], 'Le futur du Scrabble ivoirien.', 'Yamoussoukro Scrabble', true),
('boubacar-traore', 'Boubacar Traoré', (SELECT id FROM public.countries WHERE slug='mali'), '/images/player3.jpg', 7, 2045, ARRAY['Champion du Mali'], ARRAY['Mali', 'Expérience'], 'Un vétéran respecté par tous.', 'Bamako Scrabble', false),
('koffi-adzo', 'Koffi Adzo', (SELECT id FROM public.countries WHERE slug='togo'), '/images/player4.jpg', 8, 2030, ARRAY['Champion du Togo'], ARRAY['Togo', 'Précision'], 'Une précision chirurgicale sur la grille.', 'Lomé Club', false),
('herve-mbono', 'Hervé Mbono', (SELECT id FROM public.countries WHERE slug='congo'), '/images/player1.jpg', 9, 2015, ARRAY['Champion du Congo'], ARRAY['Congo', 'Tactique'], 'Maître de la défense.', 'Brazzaville Elite', false),
('patrice-houndonougbo', 'Patrice Houndonougbo', (SELECT id FROM public.countries WHERE slug='benin'), '/images/player2.jpg', 10, 2005, ARRAY['Grand Maître Béninois'], ARRAY['Bénin', 'Scolaire'], 'Formateur et joueur d''élite.', 'Cotonou Scrabble', true),
('issa-kabore', 'Issa Kaboré', (SELECT id FROM public.countries WHERE slug='burkina-faso'), '/images/player3.jpg', 11, 1985, ARRAY['Champion du Faso'], ARRAY['Burkina', 'Régularité'], 'Une régularité impressionnante.', 'Ouaga Scrabble', false),
('abdoulaye-maiga', 'Abdoulaye Maïga', (SELECT id FROM public.countries WHERE slug='niger'), '/images/player4.jpg', 12, 1970, ARRAY['Champion du Niger'], ARRAY['Niger', 'Espoir'], 'Un jeune talent prometteur.', 'Niamey Club', false),
('fallou-samb', 'Fallou Samb', (SELECT id FROM public.countries WHERE slug='senegal'), '/images/player1.jpg', 13, 1960, ARRAY['Vainqueur Coupe du Sénégal'], ARRAY['Sénégal', 'Jeune'], 'Champion junior surclassé.', 'Mbour Scrabble', false),
('aime-nguema', 'Aimé Nguema', (SELECT id FROM public.countries WHERE slug='gabon'), '/images/player2.jpg', 14, 1950, ARRAY['Finaliste Libreville'], ARRAY['Gabon'], 'Redoutable en classique.', 'Port-Gentil Club', false),
('cedric-fofana', 'Cédric Fofana', (SELECT id FROM public.countries WHERE slug='cote-ivoire'), '/images/player3.jpg', 15, 1940, ARRAY['Elite Ivoirienne'], ARRAY['Ivoirien'], 'Ancien champion scolaire.', 'Bouaké Scrabble', false),
('mathieu-zongo', 'Mathieu Zongo', (SELECT id FROM public.countries WHERE slug='burkina-faso'), '/images/player4.jpg', 16, 1930, ARRAY['Top 10 Faso'], ARRAY['Burkina'], 'Stratège né.', 'Bobo Scrabble', false),
('luc-okombo', 'Luc Okombo', (SELECT id FROM public.countries WHERE slug='congo'), '/images/player1.jpg', 17, 1920, ARRAY['Cadre National'], ARRAY['Congo'], 'Passionné du dictionnaire.', 'Pointe-Noire Club', false),
('idriss-adamou', 'Idriss Adamou', (SELECT id FROM public.countries WHERE slug='cameroun'), '/images/player2.jpg', 18, 1910, ARRAY['Espoir Camerounais'], ARRAY['Cameroun'], 'Progression fulgurante.', 'Douala Scrabble', false),
('blaise-mensah', 'Blaise Mensah', (SELECT id FROM public.countries WHERE slug='togo'), '/images/player3.jpg', 19, 1900, ARRAY['Ancien Champion'], ARRAY['Togo'], 'Le sage du circuit togolais.', 'Kara Scrabble', false),
('youssouf-diallo', 'Youssouf Diallo', (SELECT id FROM public.countries WHERE slug='mali'), '/images/player4.jpg', 20, 1890, ARRAY['Top 3 Mali'], ARRAY['Mali'], 'Joueur très combatif.', 'Kayes Scrabble', false);

-- 5. INSERT ARTICLES (15)
INSERT INTO public.articles (slug, title, excerpt, content, image, category, tags, country_id, author, author_image, published_at, read_time, featured) VALUES 
('triomphe-senegal-champaf-2025', 'Le Sénégal survole le Championnat d''Afrique 2025', 'Le Sénégal confirme sa suprématie sur le continent avec 4 médailles d''or.', '<p>Dakar a vibré au rythme des lettres chères ce weekend...</p>', '/images/tournament.jpg', 'Compétition', ARRAY['Sénégal', 'ChampAf'], (SELECT id FROM public.countries WHERE slug='senegal'), 'Amadou Diallo', '/images/player1.jpg', now(), '5 min', true),
('portrait-ndongo-samba-sylla', 'Ndongo Samba Sylla : La légende continue', 'Découvrez le parcours fascinant du numéro 1 africain.', '<p>Derrière chaque grand joueur se cache un travail acharné...</p>', '/images/player1.jpg', 'Portrait', ARRAY['Légende', 'Ndongo'], (SELECT id FROM public.countries WHERE slug='senegal'), 'Fatou Wade', '/images/player2.jpg', now() - interval '2 days', '8 min', true),
('strategie-mots-7-lettres', 'Maîtriser les benjamins et scrabbles uniques', 'Nos conseils pour optimiser vos tirages de 7 lettres.', '<p>Le Scrabble ne se limite pas à connaître des mots...</p>', '/images/scrabble-tiles.jpg', 'Stratégie', ARRAY['Tactique', 'Formation'], (SELECT id FROM public.countries WHERE slug='benin'), 'Patrice H.', '/images/player2.jpg', now() - interval '4 days', '10 min', false),
('essor-scrabble-cote-ivoire', 'L''incroyable essor du Scrabble en Côte d''Ivoire', 'Comment la CI est devenue une pépinière de champions.', '<p>Depuis 10 ans, le nombre de licenciés a triplé...</p>', '/images/country-cotedivoire.jpg', 'Culture', ARRAY['Ivoirien', 'Développement'], (SELECT id FROM public.countries WHERE slug='cote-ivoire'), 'Marc Kouamé', '/images/player3.jpg', now() - interval '6 days', '6 min', false),
('preparations-mondiaux-2026', 'En route pour les Mondiaux 2026 : Les espoirs africains', 'Les délégations africaines se préparent pour le rendez-vous mondial.', '<p>Après les succès récents, l''Afrique vise le podium mondial...</p>', '/images/community.jpg', 'Compétition', ARRAY['Mondial', 'Afrique'], (SELECT id FROM public.countries WHERE slug='cameroun'), 'Jean-Luc M.', '/images/player4.jpg', now() - interval '8 days', '7 min', true),
('scrabble-scolaire-benin', 'Le Scrabble scolaire au Bénin : Un modèle de réussite', 'Comment le jeu aide à l''apprentissage du français.', '<p>Le ministère de l''éducation a intégré le Scrabble...</p>', '/images/scrabble-tiles.jpg', 'Portrait', ARRAY['Bénin', 'Education'], (SELECT id FROM public.countries WHERE slug='benin'), 'Sophie Adjani', '/images/player1.jpg', now() - interval '10 days', '5 min', false),
('nouveautes-ods9-afrique', 'L''arrivée de l''ODS 9 en Afrique : Ce qu''il faut savoir', 'Tout sur la nouvelle version du dictionnaire officiel.', '<p>Nouveaux mots, suppressions et changements de règles...</p>', '/images/hero-scrabble.jpg', 'Stratégie', ARRAY['ODS9', 'Règles'], (SELECT id FROM public.countries WHERE slug='gabon'), 'Pierre M.', '/images/player2.jpg', now() - interval '12 days', '12 min', false),
('tournoi-amical-bamako', 'Bamako accueille un tournoi régional exceptionnel', 'Le Mali renforce les liens par les lettres.', '<p>Plus de 100 joueurs se sont réunis dans la capitale malienne...</p>', '/images/tournament.jpg', 'Compétition', ARRAY['Mali', 'Régional'], (SELECT id FROM public.countries WHERE slug='mali'), 'Ibrahim T.', '/images/player3.jpg', now() - interval '14 days', '4 min', false),
('interview-champion-cameroun', 'Interview : Jean-Marc Ndouma nous livre ses secrets', 'Le champion camerounais se confie à Scrabble Pro.', '<p>Une interview exclusive sur son régime d''entraînement...</p>', '/images/player4.jpg', 'Portrait', ARRAY['Cameroun', 'Interview'], (SELECT id FROM public.countries WHERE slug='cameroun'), 'Paul Atangana', '/images/player1.jpg', now() - interval '16 days', '15 min', false),
('histoire-scrabble-africain', 'Une brève histoire du Scrabble africain', 'Des origines à la domination actuelle.', '<p>Retour sur 50 ans de passion à travers le continent...</p>', '/images/hero-scrabble.jpg', 'Culture', ARRAY['Histoire', 'Afrique'], (SELECT id FROM public.countries WHERE slug='senegal'), 'Yara Fall', '/images/player2.jpg', now() - interval '18 days', '20 min', false),
('scrabble-numerique-togo', 'Le Togo lance sa plateforme de Scrabble en ligne', 'L''innovation digitale au service du jeu.', '<p>Désormais, les tournois peuvent se jouer à distance...</p>', '/images/community.jpg', 'Compétition', ARRAY['Togo', 'Digital'], (SELECT id FROM public.countries WHERE slug='togo'), 'Koffi T.', '/images/player3.jpg', now() - interval '20 days', '6 min', false),
('bienfaits-cognitifs-scrabble', 'Les bienfaits cognitifs du Scrabble pour les seniors', 'Plus qu''un jeu, une gymnastique mentale.', '<p>Étude sur l''impact du Scrabble sur la mémoire...</p>', '/images/scrabble-tiles.jpg', 'Stratégie', ARRAY['Santé', 'Cerveau'], (SELECT id FROM public.countries WHERE slug='niger'), 'Dr. Souna', '/images/player4.jpg', now() - interval '22 days', '8 min', false),
('club-libreville-formation', 'Le club de Libreville : Un centre de formation d''élite', 'Visite au cœur de l''usine à champions gabonaise.', '<p>Focus sur les méthodes de coaching intensif...</p>', '/images/hero-scrabble.jpg', 'Culture', ARRAY['Gabon', 'Formation'], (SELECT id FROM public.countries WHERE slug='gabon'), 'Alain N.', '/images/player1.jpg', now() - interval '24 days', '7 min', false),
('finale-nationale-burkina', 'Compte rendu : La finale nationale au Burkina Faso', 'Une finale pleine de suspense à Ouagadougou.', '<p>Le duel final a tenu toutes ses promesses...</p>', '/images/tournament.jpg', 'Compétition', ARRAY['Burkina', 'National'], (SELECT id FROM public.countries WHERE slug='burkina-faso'), 'Boureima Z.', '/images/player2.jpg', now() - interval '26 days', '5 min', false),
('femmes-scrabble-afrique', 'Le portrait des femmes qui font le Scrabble africain', 'Elles brillent et inspirent la nouvelle génération.', '<p>Rencontre avec les joueuses qui cassent les codes...</p>', '/images/player3.jpg', 'Portrait', ARRAY['Femmes', 'Inspiration'], (SELECT id FROM public.countries WHERE slug='cote-ivoire'), 'Elena Kouamé', '/images/player4.jpg', now() - interval '28 days', '9 min', true);

-- 6. INSERT COMPETITIONS (12)
INSERT INTO public.competitions (slug, name, location, country_id, start_date, end_date, status, image, description, participants, type, tags) VALUES 
('open-abidjan-2025', 'Open International d''Abidjan', 'Abidjan, Côte d''Ivoire', (SELECT id FROM public.countries WHERE slug='cote-ivoire'), now() + interval '10 days', now() + interval '14 days', 'upcoming', '/images/tournament.jpg', 'Le plus grand tournoi open de l''année en Afrique de l''Ouest.', 250, 'Open', ARRAY['Prestige', 'Cash Prize']),
('champaf-2025-dakar', 'Championnat d''Afrique 2025', 'Dakar, Sénégal', (SELECT id FROM public.countries WHERE slug='senegal'), now() - interval '2 days', now() + interval '3 days', 'ongoing', '/images/hero-scrabble.jpg', 'La compétition reine du continent.', 180, 'Championnat', ARRAY['Continental', 'Elite']),
('coupe-libreville-2024', 'Coupe de Libreville 2024', 'Libreville, Gabon', (SELECT id FROM public.countries WHERE slug='gabon'), now() - interval '30 days', now() - interval '25 days', 'completed', '/images/community.jpg', 'Un tournoi historique pour le Gabon.', 120, 'Coupe', ARRAY['Régional', 'Gabon']),
('grand-master-yaounde', 'Grand Master de Yaoundé', 'Yaoundé, Cameroun', (SELECT id FROM public.countries WHERE slug='cameroun'), now() + interval '45 days', now() + interval '47 days', 'upcoming', '/images/tournament.jpg', 'Réunion des meilleurs ratings du continent.', 32, 'Elite', ARRAY['Master', 'Top 50']),
('tournoi-fraternite-lomé', 'Tournoi de la Fraternité', 'Lomé, Togo', (SELECT id FROM public.countries WHERE slug='togo'), now() - interval '5 days', now() - interval '1 day', 'completed', '/images/scrabble-tiles.jpg', 'Célébrer l''amitié entre les peuples par les lettres.', 150, 'Amical', ARRAY['Ambiance', 'Fraternité']),
('challenge-sahel-niamey', 'Challenge du Sahel', 'Niamey, Niger', (SELECT id FROM public.countries WHERE slug='niger'), now() + interval '60 days', now() + interval '62 days', 'upcoming', '/images/player4.jpg', 'Le tournoi qui monte en puissance au Sahel.', 80, 'Challenge', ARRAY['Sahel', 'Emergent']),
('master-cotonou-2025', 'Master de Cotonou', 'Cotonou, Bénin', (SELECT id FROM public.countries WHERE slug='benin'), now() + interval '100 days', now() + interval '103 days', 'upcoming', '/images/hero-scrabble.jpg', 'Un rendez-vous incontournable pour les tacticiens.', 100, 'Master', ARRAY['Tactique', 'Bénin']),
('coupe-nationale-mali', 'Coupe Nationale du Mali', 'Bamako, Mali', (SELECT id FROM public.countries WHERE slug='mali'), now() - interval '15 days', now() - interval '10 days', 'completed', '/images/tournament.jpg', 'Le sommet du Scrabble malien.', 90, 'National', ARRAY['Mali', 'Trophée']),
('open-brazzaville', 'Open de Brazzaville', 'Brazzaville, Congo', (SELECT id FROM public.countries WHERE slug='congo'), now() + interval '5 days', now() + interval '8 days', 'upcoming', '/images/community.jpg', 'Ouvert à tous les passionnés d''Afrique Centrale.', 110, 'Open', ARRAY['Congo', 'Découverte']),
('championnat-scolaire-ouaga', 'Championnat Scolaire Pan-Africain', 'Ouagadougou, Burkina Faso', (SELECT id FROM public.countries WHERE slug='burkina-faso'), now() - interval '60 days', now() - interval '55 days', 'completed', '/images/scrabble-tiles.jpg', 'La relève du Scrabble africain s''affronte.', 300, 'Junior', ARRAY['Scolaire', 'Avenir']),
('tournoi-estival-pointe-noire', 'Tournoi Estival de Pointe-Noire', 'Pointe-Noire, Congo', (SELECT id FROM public.countries WHERE slug='congo'), now() - interval '10 days', now() + interval '2 days', 'ongoing', '/images/hero-scrabble.jpg', 'Compétition détendue en bord de mer.', 70, 'Open', ARRAY['Mer', 'Détente']),
('grand-prix-douala', 'Grand Prix de Douala', 'Douala, Cameroun', (SELECT id FROM public.countries WHERE slug='cameroun'), now() + interval '120 days', now() + interval '122 days', 'upcoming', '/images/tournament.jpg', 'Un prize pool exceptionnel pour cette première édition.', 200, 'Grand Prix', ARRAY['Cash', 'International']);

-- 7. SECURITY (RLS)
ALTER TABLE public.countries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.players ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.articles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.competitions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.submission_rate_limits ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS messages_created_at_idx ON public.messages (created_at DESC);
CREATE INDEX IF NOT EXISTS submission_rate_limits_route_window_idx ON public.submission_rate_limits (route, window_start DESC);

CREATE POLICY "Allow public read access for countries" ON public.countries FOR SELECT USING (true);
CREATE POLICY "Allow public read access for players" ON public.players FOR SELECT USING (true);
CREATE POLICY "Allow public read access for articles" ON public.articles FOR SELECT USING (true);
CREATE POLICY "Allow public read access for competitions" ON public.competitions FOR SELECT USING (true);
CREATE POLICY "Allow admin full access for countries" ON public.countries FOR ALL TO authenticated
  USING (
    COALESCE(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin'
    OR COALESCE(auth.jwt() ->> 'email', '') LIKE '%@scrabblepro.africa'
  )
  WITH CHECK (
    COALESCE(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin'
    OR COALESCE(auth.jwt() ->> 'email', '') LIKE '%@scrabblepro.africa'
  );
CREATE POLICY "Allow admin full access for players" ON public.players FOR ALL TO authenticated
  USING (
    COALESCE(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin'
    OR COALESCE(auth.jwt() ->> 'email', '') LIKE '%@scrabblepro.africa'
  )
  WITH CHECK (
    COALESCE(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin'
    OR COALESCE(auth.jwt() ->> 'email', '') LIKE '%@scrabblepro.africa'
  );
CREATE POLICY "Allow admin full access for articles" ON public.articles FOR ALL TO authenticated
  USING (
    COALESCE(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin'
    OR COALESCE(auth.jwt() ->> 'email', '') LIKE '%@scrabblepro.africa'
  )
  WITH CHECK (
    COALESCE(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin'
    OR COALESCE(auth.jwt() ->> 'email', '') LIKE '%@scrabblepro.africa'
  );
CREATE POLICY "Allow admin full access for competitions" ON public.competitions FOR ALL TO authenticated
  USING (
    COALESCE(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin'
    OR COALESCE(auth.jwt() ->> 'email', '') LIKE '%@scrabblepro.africa'
  )
  WITH CHECK (
    COALESCE(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin'
    OR COALESCE(auth.jwt() ->> 'email', '') LIKE '%@scrabblepro.africa'
  );
CREATE POLICY "Allow admin full access for messages" ON public.messages FOR ALL TO authenticated
  USING (
    COALESCE(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin'
    OR COALESCE(auth.jwt() ->> 'email', '') LIKE '%@scrabblepro.africa'
  )
  WITH CHECK (
    COALESCE(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin'
    OR COALESCE(auth.jwt() ->> 'email', '') LIKE '%@scrabblepro.africa'
  );
